import { Link } from "react-router-dom";
import { Card } from "../../components/ui/Card";
import { PageHeader } from "../../components/ui/PageHeader";

export function InstitutionDashboardPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Institution Dashboard"
        description="Bank/compliance officer workspace for synthetic transaction submission, private screening, and proof workflow initiation."
      />

      <section className="grid gap-4 lg:grid-cols-3">
        <Card>
          <h3 className="font-bold">Submit Transaction</h3>
          <p className="mt-2 text-sm text-slate-600">
            Send a synthetic AML transaction to the encryption service for pseudonymization and SMPC screening.
          </p>
          <Link to="/institution/transactions/new" className="mt-4 inline-flex rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white">
            New Transaction
          </Link>
        </Card>

        <Card>
          <h3 className="font-bold">Screening Results</h3>
          <p className="mt-2 text-sm text-slate-600">
            Review match/no-match screening outcomes generated by the confidential workflow.
          </p>
          <Link to="/institution/screening-results" className="mt-4 inline-flex rounded-xl border px-4 py-2 text-sm font-semibold">
            View Screening
          </Link>
        </Card>

        <Card>
          <h3 className="font-bold">Regulator Evidence</h3>
          <p className="mt-2 text-sm text-slate-600">
            After submission and proof generation, evidence can be reviewed by the regulator dashboard.
          </p>
          <Link to="/regulator/proofs" className="mt-4 inline-flex rounded-xl border px-4 py-2 text-sm font-semibold">
            Open Proofs
          </Link>
        </Card>
      </section>
    </div>
  );
}
