import { Card } from "../../components/ui/Card";
import { PageHeader } from "../../components/ui/PageHeader";
import { StatusBadge } from "../../components/ui/StatusBadge";

const rows = [
  {
    rec: "R.10",
    title: "Customer Due Diligence",
    evidence: "FATF_REC10 proof + screening audit events",
  },
  {
    rec: "R.11",
    title: "Record Keeping",
    evidence: "transaction + audit + proof linkage",
  },
  {
    rec: "R.16",
    title: "Payment Transparency / Travel Rule",
    evidence: "originator/beneficiary metadata proof",
  },
];

export function RegulatorComplianceReportPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Compliance Report"
        description="Report-aligned summary of FATF Recommendation evidence generated by the AML SMPC prototype."
      />

      <section className="grid gap-4 lg:grid-cols-3">
        {rows.map((row) => (
          <Card key={row.rec}>
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="text-xs font-bold uppercase text-slate-500">{row.rec}</p>
                <h3 className="mt-1 font-bold text-slate-950">{row.title}</h3>
              </div>
              <StatusBadge status="PASSED" />
            </div>
            <p className="mt-4 text-sm leading-6 text-slate-600">{row.evidence}</p>
          </Card>
        ))}
      </section>

      <Card>
        <h3 className="font-bold text-slate-950">Data Safety Statement</h3>
        <p className="mt-3 text-sm leading-6 text-slate-600">
          The regulator view displays proof and audit metadata only. It does not require raw customer identifiers,
          raw account numbers, or real customer payloads for the demo workflow.
        </p>
      </Card>
    </div>
  );
}
